[profile.default]
src = "src"
out = "out"
libs = ["node_modules"]

remappings = [
  "forge-std/=node_modules/forge-std/src",
  "ds-test/=node_modules/ds-test/src",
  "src/=src",
  "test/=test",
  "@openzeppelin/=node_modules/@openzeppelin/",
  "@openzeppelin-upgrades/contracts/=node_modules/@openzeppelin/contracts-upgradeable"
]

fs_permissions = [
  { access = "read-write", path = "./test" },
  { access = "read-write", path = "./script" },
  { access = "read", path = "./out" },
]

libraries = ["src/protocol/libraries/Secp256k1.sol:Secp256k1:0x00000000000000000000000000000000000256f1"]

[fuzz]
seed = "0x6eed"

[fmt]
bracket_spacing = true
number_underscore = "thousands"
