# Devnet2 is the smallest devnet possible. It only a single validator.
network = "devnet"
anvil_chains = ["mock_l1", "mock_l2"]

multi_iliad_evms = true
prometheus = true

[node.validator01]
[node.validator02]
