name: PR e2e test

on:
  workflow_call:

jobs:
  pr_e2e_tests:
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4
      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: 'stable'

      - name: Build binaries
        uses: goreleaser/goreleaser-action@v5
        env:
          GOOS: linux
        with:
          version: latest
          args: build --single-target --snapshot --clean --id=iliad

      - name: Build iliad image
        run: |
          cd dist/iliad_linux_amd64_v1
          docker build -f "../../client/Dockerfile" . -t "iliadops/iliad:${GITHUB_SHA::7}"

      - name: Run devnet1 e2e test
        run: |
          go install github.com/piplabs/story/e2e
          cd e2e && ./run-multiple.sh manifests/devnet1.toml

      - name: Upload failed logs
        uses: actions/upload-artifact@v4
        if: failure()
        with:
          name: failed-logs
          path: e2e/failed-logs.txt
          retention-days: 3
