name: release snapshot
# Snapshot releases on push to main.

on:
  workflow_call:

jobs:
  release-snapshot:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: stable
      - name: Login to Dockerhub container registry
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Build docker images
        uses: goreleaser/goreleaser-action@v5
        with:
          version: latest
          # Use --snapshot to build current HEAD commit (this doesn't publish images)
          args: release --snapshot --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Calculate git short sha
        id: git_ref
        run: echo "short_sha=`echo ${GITHUB_SHA::7}`" >> "$GITHUB_OUTPUT"

      - name: Push Iliad to Dockerhub
        run: |
          docker push iliadops/iliad:${GITHUB_SHA::7}
          docker push iliadops/iliad:main
