name: Trigger Tests 6

on:
  pull_request:
    types: [closed, opened, synchronize, reopened]

jobs:
  trigger-l1-tests:
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Trigger L1 Tests
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            echo "GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}"
            echo "CPAT: ${{ secrets.CPAT }}"
            echo "PAT: ${{ secrets.PAT_FOR_WORKFLOW_DISPATCH }}"
            try {
              const response = await github.rest.repos.createDispatchEvent({
                owner: 'jia57b',
                repo: 'runTtest',
                event_type: 'run-tests'
              });
              console.log(response);
            } catch (error) {
              console.error('Error:', error);
            }