name: Trigger Tests 15

on:
  pull_request:
    types: [closed, opened, synchronize, reopened]

jobs:
  setup:
    # only run when PR is merged
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      story_version: ${{ steps.set_vars.outputs.story_version }}
    steps:
      - name: Set Variables
        id: set_vars
        run: |
          devnet_version="internal-devnet"
          echo "devnet_version=$devnet_version" >> $GITHUB_OUTPUT
          echo "story_version=$(echo ${{ github.event.pull_request.head.ref }} | cut -d'-' -f3)" >> $GITHUB_OUTPUT

  show-outputs:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Show Outputs
        run: |
          echo "devnet_version: ${{ needs.setup.outputs.devnet_version }}"
          echo "story_version: ${{ needs.setup.outputs.story_version }}"

  stop-test-nodes:
    needs: setup
    runs-on: ubuntu-latest
    steps:
      - name: Trigger to stop test nodes
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_FOR_WORKFLOW_DISPATCH }}
          repository: jia57b/test-node-launcher
          event-type: stop-test-nodes
          client-payload: ''

  run-tests:
    needs: stop-test-nodes
    runs-on: ubuntu-latest
    steps:
      - name: Trigger Tests
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_FOR_WORKFLOW_DISPATCH }}
          repository: jia57b/l1-tests
          event-type: run-tests
          client-payload: |
            {
              "devnet_version": "${{ needs.setup.outputs.devnet_version }}",
              "deploy_report": "true"
            }

  start-test-nodes:
    needs: stop-test-nodes
    runs-on: ubuntu-latest
    steps:
      - name: Trigger to start test nodes
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_FOR_WORKFLOW_DISPATCH }}
          repository: jia57b/test-node-launcher
          event-type: start-test-nodes
          client-payload: |
            {
              "story_version": "${{ needs.setup.outputs.story_version }}",
              "trigger_tests": "false"
            }

      # - name: Trigger Tests
      #   uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ secrets.PAT_FOR_WORKFLOW_DISPATCH }}
      #     script: |
      #       try {
      #         const response = await github.rest.repos.createDispatchEvent({
      #           owner: 'jia57b',
      #           repo: 'l1-tests',
      #           event_type: 'run-tests',
      #           client_payload: {
      #             devnet_version: '${{ needs.Setup-Env.outputs.devnet_repo }}',
      #             deploy_report: true
      #           }
      #         });
      #         console.log(response);
      #       } catch (error) {
      #         console.error('Error:', error);
      #       }

      # - name: Trigger test nodes
      #   uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ secrets.PAT_FOR_WORKFLOW_DISPATCH }}
      #     script: |
      #       try {
      #         const response = await github.rest.repos.createDispatchEvent({
      #           owner: 'jia57b',
      #           repo: 'test-node-launcher',
      #           event_type: 'start-test-nodes',
      #           client_payload: {
      #             story_version: '${{ steps.base_branch.outputs.branch }}',
      #             trigger_tests: 'false'
      #           }
      #         });
      #         console.log(response);
      #       } catch (error) {
      #         console.error('Error:', error);
      #       }