name: Trigger Tests 7

on:
  pull_request:
    types: [closed, opened, synchronize, reopened]

jobs:
  trigger-l1-tests:
    # only run when PR is merged
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: get the PR base branch
        id: base_branch
        run: |
          echo "${{ github.base_ref }}"
          echo "::set-output name=branch::$(echo ${{ github.base_ref }} | cut -d'/' -f3)"

      - name: Trigger L1 Tests
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.PAT_FOR_WORKFLOW_DISPATCH }}
          script: |
            try {
              const response = await github.rest.repos.createDispatchEvent({
                owner: 'jia57b',
                repo: 'test-node-launcher',
                event_type: 'start-test-nodes',
                client_payload: {
                  geth_version: 'v1.0.1',
                  story_version: '${{ steps.base_branch.outputs.branch }}',
                  network_launcher_branch: 'yao/old_timelock/02_08',
                }
              });
              console.log(response);
            } catch (error) {
              console.error('Error:', error);
            }