name: Trigger Tests 14

on:
  pull_request:
    types: [closed, opened, synchronize, reopened]

jobs:
  trigger-l1-tests:
    # only run when PR is merged
    # if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: get the PR base branch
        id: base_branch
        run: |
          echo "${{ github.base_ref }}"
          echo "::set-output name=branch::$(echo ${{ github.base_ref }} | cut -d'/' -f3)"
          # story_version: '${{ steps.base_branch.outputs.branch }}'


      - name: Trigger Tests
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_FOR_WORKFLOW_DISPATCH }}
          repository: jia57b/l1-tests
          event-type: run-tests
          client-payload: '{"devnet_version": "${{ needs.Setup-Env.outputs.devnet_version }}", "deploy_report": "false"}'

      - name: Trigger test nodes
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PAT_FOR_WORKFLOW_DISPATCH }}
          repository: jia57b/test-node-launcher
          event-type: start-test-nodes
          client-payload: '{"story_version": "${{ steps.base_branch.outputs.branch }}", "trigger_tests": "false"}'
  

      # - name: Trigger Tests
      #   uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ secrets.PAT_FOR_WORKFLOW_DISPATCH }}
      #     script: |
      #       try {
      #         const response = await github.rest.repos.createDispatchEvent({
      #           owner: 'jia57b',
      #           repo: 'l1-tests',
      #           event_type: 'run-tests',
      #           client_payload: {
      #             devnet_version: '${{ needs.Setup-Env.outputs.devnet_repo }}',
      #             deploy_report: true
      #           }
      #         });
      #         console.log(response);
      #       } catch (error) {
      #         console.error('Error:', error);
      #       }

      # - name: Trigger test nodes
      #   uses: actions/github-script@v6
      #   with:
      #     github-token: ${{ secrets.PAT_FOR_WORKFLOW_DISPATCH }}
      #     script: |
      #       try {
      #         const response = await github.rest.repos.createDispatchEvent({
      #           owner: 'jia57b',
      #           repo: 'test-node-launcher',
      #           event_type: 'start-test-nodes',
      #           client_payload: {
      #             story_version: '${{ steps.base_branch.outputs.branch }}',
      #             trigger_tests: 'false'
      #           }
      #         });
      #         console.log(response);
      #       } catch (error) {
      #         console.error('Error:', error);
      #       }